baseURL = "/"
languageCode = "en-us"
title = "(DD)uplicate! A Decentralized home for all GME DD"
theme = "archie"
staticDir = ["static", "static/img"]
relativeURLS = true
uglyURLs = true

[params]
    mode = "dark"
    
